name: Court Data Pipeline

on:
  # schedule:
  #   # Run at 2:00 AM UTC every day
  #   - cron: "0 2 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Ensure directories exist
        run: |
          mkdir -p ./local_hc_metadata
          mkdir -p ./data

      - name: Run court data pipeline
        run: python download.py --sync-s3

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            *.log
            captcha-failures/
            captcha-tmp/
            track.json
          retention-days: 7
