name: Court Data Pipeline

on:
  schedule:
    # Run at 2:00 AM UTC every day
    - cron: "0 2 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 tqdm pyarrow pandas
          # Install any other dependencies your script needs
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Change to the appropriate region
          role-duration-seconds: 1200
          role-session-name: GitHubActions

      - name: Create AWS credentials file with profile
        run: |
          mkdir -p ~/.aws
          echo "[dattam-high-anshu]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=ap-south-1" >> ~/.aws/credentials

      - name: Ensure directories exist
        run: |
          mkdir -p ./local_hc_metadata
          mkdir -p ./data

      - name: Run court data pipeline
        run: python z3-up.py

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            *.log
            captcha-failures/
            captcha-tmp/
            track.json
          retention-days: 7
